### ISSUE TITLE
TypeError: 'Pyfhel.PyCtxt.PyCtxt' object is not iterable

### ISSUE THREAD

**Issue by klqsebxdbsyn** [AI-Tech-Research-Lab/PyCrCNN#18]
hello,
When processing a one-dimensional signal using one-dimensional convolution, the following error occurred based on the method provided in your code for the conv1d model of PyCrCNN
Traceback (most recent call last):
  File "E:\pytorch\experiment\8.1ECG\load.py", line 642, in <module>
    y_pred, y_true = make_test_stage(test_dataloader,lenet1_approx_encoded)
  File "E:\pytorch\experiment\8.1ECG\load.py", line 568, in make_test_stage
    cls_prediction = model(data)
  File "E:\pytorch\experiment\8.1ECG\pycrcnn\model\sequential.py", line 113, in __call__
    x = layer(x)
  File "E:\pytorch\experiment\8.1ECG\pycrcnn\convolutional\convolutional_layer.py", line 197, in __call__
    result = np.array([[np.sum([convolute1d(ts_layer, filter_layer, self.stride)
  File "E:\pytorch\experiment\8.1ECG\pycrcnn\convolutional\convolutional_layer.py", line 197, in <listcomp>
    result = np.array([[np.sum([convolute1d(ts_layer, filter_layer, self.stride)
  File "E:\pytorch\experiment\8.1ECG\pycrcnn\convolutional\convolutional_layer.py", line 198, in <listcomp>
    for ts_layer, filter_layer in zip(_ts, _filter)], axis=0)
TypeError: 'Pyfhel.PyCtxt.PyCtxt' object is not iterable

What should I do with the one-dimensional convolutional PyCrCNN model?
How can this issue be resolved?

**Comment by AlexMV12** [comment]
Hello,

Can you provide a minimum code to reproduce the problem? Even with a random tensor.
It looks like some dimension in the tensor is missing.
